In [1]:
import pandas as pd
import numpy as np
import inspect
import os

In [16]:
file_path = inspect.getfile(inspect.currentframe())
file_direction = os.path.dirname(os.path.abspath(file_path))
offertagging = os.path.join(file_direction, './Demo3/RecommandSystem/MJ_OFFER.xlsx')
usertagging = os.path.join(file_direction, './Demo3/RecommandSystem/MJ_TAG.xlsx')

In [17]:
usertagging = pd.read_excel(usertagging)
offertagging = pd.read_excel(offertagging)

In [18]:
offertagging = offertagging.drop_duplicates().reset_index(drop=True)

In [19]:
offertagging = offertagging.loc[:149]
usertagging = usertagging.loc[:149]

In [21]:
offertagging.to_csv('offer_testdata.csv', sep = '\t', index=False)
usertagging.to_csv('user_testdata.csv', sep = '\t',index=False)

In [23]:
offer_counts = offertagging.groupby('ID').OFFER_ID.count()

In [48]:
id_counts = offertagging.groupby('OFFER_ID').ID.count()

In [50]:
offertagging

       ID  LABEL_ID OFFER_ID
0     864        54  OFF0007
1     864       233  OFF0007
2     864       213  OFF0007
3     864        56  OFF0007
4     864        63  OFF0007
5     864       203  OFF0007
6     864       216  OFF0007
7     864       108  OFF0007
8    1160        34  OFF0014
9    1160       123  OFF0014
10   1160       233  OFF0014
11   1160       120  OFF0014
12   1160        17  OFF0014
13   1160       206  OFF0014
14   1160       155  OFF0014
15   1160        21  OFF0014
16   1160       125  OFF0014
17   1160       157  OFF0014
18    936       134  OFF0005
19    936        47  OFF0005
20    936        54  OFF0005
21    936       144  OFF0005
22    936       233  OFF0005
23    936       183  OFF0005
24    936       227  OFF0005
25    936       203  OFF0005
26    936        89  OFF0005
27    100       103  OFF0022
28    100        47  OFF0005
29    100        54  OFF0005
..    ...       ...      ...
120   176        63  OFF0007
121   176       203  OFF0007
122   176       216  OFF0007
123   176       108  OFF0007
124   222       103  OFF0023
125   222        49  OFF0023
126   222       235  OFF0023
127   222       135  OFF0023
128  1191       103  OFF0023
129  1191       117  OFF0010
130  1191       200  OFF0010
131  1191        54  OFF0010
132  1191       233  OFF0010
133  1191        55  OFF0010
134  1191       124  OFF0010
135  1191        44  OFF0010
136  1191       166  OFF0010
137  1191        27  OFF0010
138  1191        62  OFF0010
139  1191        42  OFF0010
140  1191       238  OFF0010
141  1191        49  OFF0023
142  1191       235  OFF0023
143  1191       135  OFF0023
144  1441       229  OFF0025
145  1441        43  OFF0016
146  1441       233  OFF0016
147  1441        12  OFF0016
148  1441        11  OFF0016
149  1441         9  OFF0016

[150 rows x 3 columns]

df = usertagging[~usertagging.ID.isin(offer_counts[offer_counts < 2].index.tolist())]

In [5]:
import redis
import json

In [6]:
redis_conn = redis.Redis(host='localhost',port=6379,db=0)

In [ ]:
import pickle
with open('tag_mapping.pickle', 'rb') as f3:
    tag_mapping = pickle.load(f3)

In [7]:
test = model.predict(json.loads(redis_conn.get(1)))

In [11]:
sorted(usertagging.UTID.unique())

[u'TG0014',
 u'TG0015',
 u'TG0016',
 u'TG0017',
 u'TG0018',
 u'TG0019',
 u'TG0020',
 u'TG0021',
 u'TG0022',
 u'TG0023',
 u'TG0026',
 u'TG0027',
 u'TG0028',
 u'TG0029',
 u'TG0030',
 u'TG0031',
 u'TG0032',
 u'TG0033',
 u'TG0035',
 u'TG0036',
 u'TG0038',
 u'TG0041',
 u'TG0042',
 u'TG0043',
 u'TG0044',
 u'TG0045',
 u'TG0046',
 u'TG0047',
 u'TG0048',
 u'TG0086',
 u'TG0087',
 u'TG0088',
 u'TG0089',
 u'TG0090',
 u'TG0091',
 u'TG0092',
 u'TG0093',
 u'TG0094',
 u'TG0095',
 u'TG0096',
 u'TG0109',
 u'TG0110',
 u'TG0111',
 u'TG0112',
 u'TG0113',
 u'TG0118',
 u'TG0119',
 u'TG0120',
 u'TG0121',
 u'TG0122',
 u'TG0123',
 u'TG0124',
 u'TG0125',
 u'TG0126',
 u'TG0127',
 u'TG0128',
 u'TG0129',
 u'TG0130',
 u'TG0131',
 u'TG0132',
 u'TG0133',
 u'TG0134',
 u'TG0135',
 u'TG0136',
 u'TG0137',
 u'TG0138',
 u'TG0139',
 u'TG0140',
 u'TG0202',
 u'TG0203',
 u'TG0204',
 u'TG0205',
 u'TG0206',
 u'TG0207',
 u'TG0208',
 u'TG0209',
 u'TG0210',
 u'TG0246',
 u'TG0247',
 u'TG0248',
 u'TG0249',
 u'TG0250',
 u'TG0251',
 u'TG0252',
 u'TG0254',
 u'TG0255',
 u'TG0256',
 u'TG0257',
 u'TG0258',
 u'TG0259',
 u'TG0260',
 u'TG0261',
 u'TG0262',
 u'TG0268',
 u'TG0269',
 u'TG0270',
 u'TG0271',
 u'TG0272',
 u'TG0273',
 u'TG0274',
 u'TG0275',
 u'TG0276',
 u'TG0277',
 u'TG0278',
 u'TG0279',
 u'TG0282',
 u'TG0283',
 u'TG0284',
 u'TG0288',
 u'TG0289',
 u'TG0292',
 u'TG0293',
 u'TG0298',
 u'TG0311',
 u'TG0312',
 u'TG0314',
 u'TG0316',
 u'TG0317',
 u'TG0321',
 u'TG0326',
 u'TG0327',
 u'TG0329',
 u'TG0330',
 u'TG0342',
 u'TG0343',
 u'TG0344',
 u'TG0345',
 u'TG0346',
 u'TG0350',
 u'TG0351',
 u'TG0354',
 u'TG0355',
 u'TG0356',
 u'TG0357',
 u'TG0363',
 u'TG0364',
 u'TG0365',
 u'TG0366',
 u'TG0372',
 u'TG0374',
 u'TG0375',
 u'TG0376',
 u'TG0378',
 u'TG0379',
 u'TG0380',
 u'TG0385',
 u'TG0387',
 u'TG0388',
 u'TG0389',
 u'TG0390',
 u'TG0397',
 u'TG0398',
 u'TG0400',
 u'TG0401',
 u'TG0402',
 u'TG0403',
 u'TG0404',
 u'TG0405',
 u'TG0406',
 u'TG0407',
 u'TG0411',
 u'TG0412',
 u'TG0415',
 u'TG0416']

In [ ]:
sort_data = sorted(range(len(test)), key=lambda x: test[x])

In [ ]:
key = sorted(test)
sort_data = sorted(range(len(test)), key=lambda x: test[x])

In [ ]:
import pickle
with open('reverse_offertag.pickle', 'rb') as f4:
    reverse_offertag = pickle.load(f4)

In [ ]:
offer = []
for i in test:
    offer.append(reverse_offertag[i])

In [ ]:
len(reverse_offertag)

In [ ]:
offer_table = np.zeros(len(reverse_offertag))
for i in offer:
    offer_table[i] = 1

In [5]:
offer_table.shape

NameError: name 'offer_table' is not defined

In [ ]:
data = pd.read_csv('../OFFERTAG_MAPPING.csv')

In [ ]:
data_table = data.pivot_table(index='OFFER_ID', columns='LABEL_ID', values='IND').fillna(0)

In [ ]:
data_table.index.values

In [ ]:
data_table.values.shape

In [ ]:
from sklearn.metrics import pairwise
offer_similarity = pairwise.cosine_similarity(offer_table.reshape(1,-1), data_table)

In [ ]:
offer_similarity